const templateData = [
  {
    name: "Education",
    tasks: [
      // {
      //   title: "Do first Education Task",
      //   type: "system" or "user",
      //   type: "system",
      //   complete: false,
      //   completed: false,
      //   points: 1,
      //   steps: [
      //     {
      //       id: 0,
      //       title: "step 1",
      //       type: "system",
      //       complete: false,
      //       completed: false,
      //       points: 1,
      //     },
      //   ],
      // },
      {
        //individual new task from here
        title: "Set Goals",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      }, //to here
      {
        title: "Registration",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Assessment",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Consultation",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Attend Classes",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Graduate",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
    ],
  },
  {
    name: "Employment",
    tasks: [
      {
        title: "Establish Eligibility",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Assess Career Goals",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Preparation Phase",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [
          {
            id: 0,
            title: "Step 1: Employment Plan",
            type: "system",
            complete: false,
            completed: false,
            points: 1,
          },
        ],
      },
      {
        title: "Job Search",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Training/Upskililng",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Securing Employment",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
    ],
  },
  {
    name: "Financial",
    tasks: [
      {
        title: "Intake",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Credit Assessment",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Set Goals",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Create a Budget",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Financial Asset",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Emergency Fund",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
    ],
  },
  {
    name: "Healthcare",
    tasks: [
      {
        title: "Get a Physical",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Nutrition/Exercise",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Dental",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Vision",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Mental Health",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Choose Your Own",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
    ],
  },
  {
    name: "Housing",
    tasks: [
      {
        title: "Assess Needs",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Budget",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Security Deposit",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Search",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Apply for Housing",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
      {
        title: "Lease-up",
        type: "system",
        complete: false,
        completed: false,
        points: 1,
        steps: [],
      },
    ],
  },
];

export default templateData;
